CREATE PROC FI_SP_DelBenefic
    @ID BIGINT
AS
BEGIN
    BEGIN TRANSACTION

    BEGIN TRY
        DELETE FROM BENEFICIARIOS
        WHERE ID = @ID;

        COMMIT TRANSACTION;
    END TRY

    BEGIN CATCH
        ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;